"""
Stage 4 (classify_results) and the top-level reconcile() orchestrator --
v10, restructured around the two-layer model:

  DISPOSITION (from resolve_assignments): the single, authoritative,
  mutually-exclusive accounting category per order. Computed once.

  FINDINGS (this module): zero or more per claim/order, generated by
  reading disposition and edges. A finding may reference an order's
  disposition for context, but NEVER changes it. This is the fix for the
  counterexample that motivated this rewrite: a REJECTED claim's
  contradiction finding and an unrelated ambiguity finding can both
  legitimately reference the same order without fighting over who "owns"
  its category, because no finding has the power to set it.
"""
from __future__ import annotations

from datetime import datetime, timedelta

from reconcile_v12 import (
    InternalClaim, BrokerOrder, Edge, Assignment, ExecutionEligibility,
    EvidenceTier, OrderDisposition, Result, PositionState, MatchConfidence,
    Timeliness, CaseStatus, Interpretation, FailureType, ReasonCode,
    ReconciliationResult, REJECTED_COMPATIBLE_STATUSES, FILLED_STATUSES,
    normalize_inputs, build_evidence_graph, resolve_assignments, _timeliness,
    assign_stable_ids, assign_claim_stable_ids,
)


def classify_results(claims, broker_orders, eligibility, edges, assignments, disposition, now):
    results: list[ReconciliationResult] = []

    edges_by_claim: dict[int, list[Edge]] = {}
    for e in edges:
        edges_by_claim.setdefault(e.claim_idx, []).append(e)

    for i, claim in enumerate(claims):
        age = now - claim.claimed_at
        timeliness = _timeliness(age)
        elig = eligibility[i]

        if elig == ExecutionEligibility.EXECUTION_SKIPPED:
            if claim.caller_interpretation == Interpretation.SKIPPED:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.DUPLICATE_BLOCKED,
                    reason_codes=claim.known_reason_codes or (ReasonCode.NONE,),
                    case_status=CaseStatus.NO_CASE, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.NOT_APPLICABLE,
                    evidence=f"Correctly-handled SKIP for '{claim.request_id}' -- excluded "
                             f"from the evidence graph entirely.",
                ))
            else:
                reasons = claim.known_reason_codes or (ReasonCode.CALLER_IGNORED_SKIP,)
                if ReasonCode.CALLER_IGNORED_SKIP not in reasons:
                    reasons = reasons + (ReasonCode.CALLER_IGNORED_SKIP,)
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.MISSING_EXTERNALLY,
                    reason_codes=reasons,
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.NOT_APPLICABLE,
                    evidence=f"SafeAgent's guard decision for '{claim.request_id}' remains "
                             f"SKIP -- the caller's interpretation was wrong, but no "
                             f"external execution should be inferred from that error alone.",
                ))
            continue

        res = assignments[i]

        if elig == ExecutionEligibility.EXECUTION_REJECTED:
            contradiction_orders = [
                e.order_idx for e in edges_by_claim.get(i, [])
                if e.tier in (EvidenceTier.FULL_IDENTIFIER, EvidenceTier.PARTIAL_IDENTIFIER)
                and broker_orders[e.order_idx].status in FILLED_STATUSES
            ]
            if contradiction_orders:
                # Deterministic, order-independent choice when multiple
                # filled orders match: pick by stable_id, not "whichever
                # came first in the edges list" -- the same class of
                # permutation-dependence bug fixed earlier for the
                # standalone conflict finding's correlation.
                order_idx = min(contradiction_orders, key=lambda oi: broker_orders[oi].stable_id)
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=broker_orders[order_idx],
                    result=Result.CONTRADICTION,
                    reason_codes=(ReasonCode.REJECTION_EXECUTION_CONTRADICTION,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.STRONG_FULL,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Internal evidence says '{claim.request_id}' was rejected, "
                             f"but a compatible external record shows it filled. This "
                             f"order's own accounting disposition is independently "
                             f"{disposition[order_idx].value} -- this finding does not "
                             f"change that.",
                    accounting_category=disposition[order_idx],
                ))

            if res.kind == "assigned":
                order = broker_orders[res.order_idx]
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=order,
                    result=Result.REJECTED,
                    reason_codes=(ReasonCode.BROKER_REJECTED,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.STRONG_FULL,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Broker explicitly rejected '{claim.request_id}', matched to "
                             f"a compatible rejected/canceled external record.",
                    accounting_category=disposition[res.order_idx],
                ))
            elif res.kind == "ambiguous":
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.REJECTED,
                    reason_codes=(ReasonCode.BROKER_REJECTED, ReasonCode.AMBIGUOUS_MULTIPLE_IDENTIFIER_MATCHES),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Broker rejected '{claim.request_id}'. Separately, candidate "
                             f"rejected/canceled records were themselves ambiguous.",
                    involved_order_stable_ids=tuple(broker_orders[o].stable_id for o in res.involved_order_indices),
                ))
            elif res.kind == "conflict":
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.REJECTED,
                    reason_codes=(ReasonCode.BROKER_REJECTED, ReasonCode.IDENTIFIER_CONFLICT),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Broker rejected '{claim.request_id}'. Separately, a candidate "
                             f"record conflicted on identifiers.",
                    involved_order_stable_ids=tuple(broker_orders[o].stable_id for o in res.involved_order_indices),
                ))
            elif not contradiction_orders:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.REJECTED,
                    reason_codes=(ReasonCode.BROKER_REJECTED,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Broker explicitly rejected '{claim.request_id}'. No matching "
                             f"external record at all.",
                ))
            continue

        if res.kind == "assigned":
            order = broker_orders[res.order_idx]
            confidence = {EvidenceTier.FULL_IDENTIFIER: MatchConfidence.STRONG_FULL,
                          EvidenceTier.PARTIAL_IDENTIFIER: MatchConfidence.STRONG_PARTIAL,
                          EvidenceTier.WEAK_HEURISTIC: MatchConfidence.WEAK_HEURISTIC}[res.tier]
            reasons = (ReasonCode.PARTIAL_IDENTIFIER_EVIDENCE,) if res.tier == EvidenceTier.PARTIAL_IDENTIFIER else (ReasonCode.NONE,)
            if order.status in FILLED_STATUSES:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=order,
                    result=Result.CONFIRMED, reason_codes=reasons,
                    case_status=CaseStatus.NO_CASE, timeliness=timeliness,
                    match_confidence=confidence,
                    position_state=PositionState.NOT_APPLICABLE,
                    evidence=f"Matched a filled broker order ({res.tier.value} confidence).",
                    accounting_category=disposition[res.order_idx],
                ))
            else:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=order,
                    result=Result.UNCERTAIN,
                    reason_codes=(ReasonCode.AMBIGUOUS_PROVIDER_RESPONSE,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=confidence,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Matched broker order has status '{order.status}'.",
                    accounting_category=disposition[res.order_idx],
                ))

        elif res.kind == "ambiguous":
            reason = (ReasonCode.AMBIGUOUS_MULTIPLE_IDENTIFIER_MATCHES
                      if (claim.broker_order_id or claim.client_order_id)
                      else ReasonCode.AMBIGUOUS_MULTIPLE_WEAK_MATCHES)
            results.append(ReconciliationResult(
                claim=claim, matched_broker_order=None,
                result=Result.UNCERTAIN, reason_codes=(reason,),
                case_status=CaseStatus.OPEN, timeliness=timeliness,
                match_confidence=MatchConfidence.NONE,
                position_state=PositionState.UNKNOWN,
                evidence=f"'{claim.request_id}' has multiple equally-optimal candidates "
                         f"with no way to prefer one.",
                involved_order_stable_ids=tuple(broker_orders[o].stable_id for o in res.involved_order_indices),
            ))

        elif res.kind == "conflict":
            results.append(ReconciliationResult(
                claim=claim, matched_broker_order=None,
                result=Result.UNCERTAIN,
                reason_codes=(ReasonCode.IDENTIFIER_CONFLICT,),
                case_status=CaseStatus.OPEN, timeliness=timeliness,
                match_confidence=MatchConfidence.NONE,
                position_state=PositionState.UNKNOWN,
                evidence=f"Every remaining candidate for '{claim.request_id}' conflicted "
                         f"on at least one identifier.",
                involved_order_stable_ids=tuple(broker_orders[o].stable_id for o in res.involved_order_indices),
            ))

        else:
            if claim.caller_interpretation == Interpretation.SUCCESS:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.MISSING_EXTERNALLY,
                    reason_codes=(ReasonCode.BROKER_MATCH_NOT_FOUND,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"Internal log records '{claim.request_id}' as a successful "
                             f"{claim.stage}, but no matching broker order exists.",
                ))
            else:
                results.append(ReconciliationResult(
                    claim=claim, matched_broker_order=None,
                    result=Result.UNCERTAIN,
                    reason_codes=(ReasonCode.BROKER_MATCH_NOT_FOUND,),
                    case_status=CaseStatus.OPEN, timeliness=timeliness,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.UNKNOWN,
                    evidence=f"No broker order found for '{claim.request_id}' and no clear reason why.",
                ))

    for i, order in enumerate(broker_orders):
        d = disposition[i]
        if d == OrderDisposition.UNMATCHED:
            results.append(ReconciliationResult(
                claim=None, matched_broker_order=order,
                result=Result.UNRECORDED_INTERNALLY,
                reason_codes=(ReasonCode.UNMATCHED_BROKER_ORDER,),
                case_status=CaseStatus.OPEN, timeliness=Timeliness.CURRENT,
                match_confidence=MatchConfidence.NONE,
                position_state=PositionState.NOT_APPLICABLE,
                evidence=f"Broker order ({order.qty} {order.symbol} {order.side}) has no "
                         f"relationship to any executing claim.",
                accounting_category=d,
            ))
        elif d == OrderDisposition.IDENTIFIER_CONFLICT:
            already_primary = any(
                (r.matched_broker_order is order or order.stable_id in r.involved_order_stable_ids)
                and any(rc in (ReasonCode.IDENTIFIER_CONFLICT, ReasonCode.REJECTION_EXECUTION_CONTRADICTION)
                        for rc in r.reason_codes)
                for r in results
            )
            if not already_primary:
                conflicting_claim_indices = [
                    e.claim_idx for e in edges
                    if e.order_idx == i and e.tier == EvidenceTier.IDENTIFIER_CONFLICT
                ]
                # Deterministic, order-independent choice: when multiple
                # claims equally conflict with this order, correlate to
                # whichever has the alphabetically-first claim STABLE_ID --
                # not request_id (a label, not identity: two distinct
                # claims may share one, per D26) and not "whichever
                # happened to be first in the edges list", which depends
                # purely on input order and was a real, if subtle,
                # permutation-dependence bug.
                correlation = (
                    min((claims[idx].stable_id for idx in conflicting_claim_indices))
                    if conflicting_claim_indices else None
                )
                results.append(ReconciliationResult(
                    claim=None, matched_broker_order=order,
                    result=Result.UNCERTAIN,
                    reason_codes=(ReasonCode.EXTERNAL_IDENTIFIER_CONFLICT,),
                    case_status=CaseStatus.OPEN, timeliness=Timeliness.CURRENT,
                    match_confidence=MatchConfidence.NONE,
                    position_state=PositionState.NOT_APPLICABLE,
                    evidence=f"Broker order conflicts with a claim's identifiers but was "
                             f"not that claim's primary reported record.",
                    correlation_id=correlation,
                    accounting_category=d,
                ))

    return results


def reconcile(claims, broker_orders, now, match_tolerance=timedelta(minutes=5)):
    assign_stable_ids(broker_orders)
    assign_claim_stable_ids(claims)
    eligibility = normalize_inputs(claims, broker_orders)
    edges = build_evidence_graph(claims, broker_orders, eligibility)
    assignments, disposition = resolve_assignments(edges, len(claims), len(broker_orders))
    return classify_results(claims, broker_orders, eligibility, edges, assignments, disposition, now)


def reconcile_with_disposition(claims, broker_orders, now, match_tolerance=timedelta(minutes=5)):
    assign_stable_ids(broker_orders)
    assign_claim_stable_ids(claims)
    eligibility = normalize_inputs(claims, broker_orders)
    edges = build_evidence_graph(claims, broker_orders, eligibility)
    assignments, disposition = resolve_assignments(edges, len(claims), len(broker_orders))
    results = classify_results(claims, broker_orders, eligibility, edges, assignments, disposition, now)
    return results, disposition


def summarize(results):
    counts = {}
    for r in results:
        counts[r.result.value] = counts.get(r.result.value, 0) + 1
    return counts


def summarize_incidents(results):
    groups = {}
    for r in results:
        if r.correlation_id is not None:
            key = r.correlation_id
        elif r.claim is not None:
            # claim.stable_id, not request_id -- two distinct claims may
            # share a request_id (D26), which would otherwise merge their
            # findings into one incident and undercount.
            key = r.claim.stable_id
        else:
            key = f"standalone:{id(r)}"
        groups.setdefault(key, []).append(r)
    counts = {"OPEN": 0, "CLEAN": 0}
    for group in groups.values():
        if any(r.case_status == CaseStatus.OPEN for r in group):
            counts["OPEN"] += 1
        else:
            counts["CLEAN"] += 1
    return counts