#!/usr/bin/env python3
"""ledger_server.py -- standalone, out-of-process authoritative effect ledger.

Run as a genuinely separate OS process (never imported, never run in-thread
with the worker or the parent). Exposes exactly two capability classes over
HTTP on 127.0.0.1, distinguished ONLY by which bearer token the caller holds:

  RECORD capability (record_token):
    POST /record   {logical_id, attempt_id}  -> appends one entry, returns
                    {ok: true, seq, server_ts}. That is the ENTIRE worker-
                    facing surface. There is no endpoint under this token
                    that reads, counts, resets, or seals anything -- those
                    endpoints check for the control_token specifically and
                    reject the record_token with 403, proven by
                    test_v3.py::test_worker_cannot_use_control_channel.

  CONTROL capability (control_token):
    POST /control/reset  -> clears all entries, unseals. Only ever called
                    by the parent, before a trial starts.
    POST /control/seal   -> marks the ledger sealed. After sealing, /record
                    is permanently rejected (409) for the rest of this
                    process's life -- enforces "the worker cannot write
                    after the parent has started reading."
    GET  /control/read   -> returns the full authoritative entry list plus
                    seal state. Only ever called by the parent, only after
                    the worker subprocess has fully exited and the ledger
                    has been sealed.

The worker process is launched with ONLY the record_token in its argv/env.
The control_token is generated by the parent and never leaves the parent
process -- it is not written to any file the worker can read, not passed
as a CLI argument to the worker, not exported into the worker's
environment. This is a real capability boundary enforced by the server's
own authorization check on every request, not merely "the worker wasn't
told the URL."
"""
from __future__ import annotations

import json
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


class _State:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.entries: list[dict] = []
        self.sealed = False
        self.next_seq = 1


def make_handler(record_token: str, control_token: str, state: _State):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):  # silence default stderr access log
            pass

        def _send_json(self, status: int, payload: dict) -> None:
            body = json.dumps(payload).encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def _bearer(self) -> str | None:
            h = self.headers.get("Authorization", "")
            return h[len("Bearer "):] if h.startswith("Bearer ") else None

        def do_POST(self):
            token = self._bearer()
            length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(length) if length else b""
            try:
                payload = json.loads(raw) if raw else {}
            except json.JSONDecodeError:
                self._send_json(400, {"error": "malformed_json"})
                return

            if self.path == "/record":
                if token != record_token:
                    self._send_json(403, {"error": "record_forbidden"})
                    return
                with state.lock:
                    if state.sealed:
                        self._send_json(409, {"error": "ledger_sealed"})
                        return
                    entry = {
                        "seq": state.next_seq,
                        "logical_id": payload.get("logical_id"),
                        "attempt_id": payload.get("attempt_id"),
                        "server_ts": time.time(),
                    }
                    state.next_seq += 1
                    state.entries.append(entry)
                self._send_json(200, {"ok": True, **entry})
                return

            if self.path == "/control/reset":
                if token != control_token:
                    self._send_json(403, {"error": "control_forbidden"})
                    return
                with state.lock:
                    state.entries = []
                    state.sealed = False
                    state.next_seq = 1
                self._send_json(200, {"ok": True})
                return

            if self.path == "/control/seal":
                if token != control_token:
                    self._send_json(403, {"error": "control_forbidden"})
                    return
                with state.lock:
                    state.sealed = True
                self._send_json(200, {"ok": True, "sealed": True})
                return

            self._send_json(404, {"error": "not_found"})

        def do_GET(self):
            token = self._bearer()
            if self.path == "/control/read":
                if token != control_token:
                    self._send_json(403, {"error": "control_forbidden"})
                    return
                with state.lock:
                    self._send_json(200, {
                        "ok": True, "sealed": state.sealed,
                        "entries": list(state.entries),
                    })
                return
            if self.path == "/healthz":
                self._send_json(200, {"ok": True})
                return
            self._send_json(404, {"error": "not_found"})

    return Handler


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, required=True)
    ap.add_argument("--record-token", required=True)
    ap.add_argument("--control-token", required=True)
    args = ap.parse_args()

    state = _State()
    handler = make_handler(args.record_token, args.control_token, state)
    httpd = ThreadingHTTPServer(("127.0.0.1", args.port), handler)
    # Signal readiness on stdout for the parent to synchronize on, without
    # ever printing either token.
    print("LEDGER_READY", flush=True)
    httpd.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
